# Copyright New Relic, Inc.
# SPDX-License-Identifier: Apache-2.0
---

name: "PHP Init Container CI"

concurrency:
  group: ${{ github.ref_name || github.ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'src/php/**'
      - 'tests/php/**'
      - '.github/workflows/php.yml'
  push:
    paths:
      - 'src/php/**'
      - 'tests/php/**'
      - '.github/workflows/php.yml'
    branches:
      - main
    # Do not run when a tag is created.
    tags-ignore:
      - "**"
  release:
    types:
      - published

jobs:
  test:
    if: github.event_name != 'release' || (github.event_name == 'release' && endsWith(github.ref, '_php')) # Skip everything if this isn't PHP
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      INITCONTAINER_LANGUAGE: php

  publish:
    if: github.event_name == 'release' && endsWith(github.ref, '_php') # Skip everything if this isn't PHP
    needs: test
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        libc: ["glibc", "musl"]
    with:
      INITCONTAINER_LANGUAGE: php
      DOCKER_IMAGE_TAG_SUFFIX: ${{ matrix.libc }}
      DOCKER_IMAGE_TAG_IS_DEFAULT_SUFFIX: ${{ matrix.libc == 'glibc' }}
      BUILD_ARGS: LIBC=${{ matrix.libc }}
